name: second workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  
jobs:
  jobname:
   runs-on: ubuntu-latest
   steps:
     -uses: actions/checkout@v3
     -name: Run a one-line script
      run: echo hello,himani batch8

     -name: run a multi-line script
      run: |
        echo hi,
        echo you.   