

name: second workflow


on:
  
  
  

  
  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v3

      
      - name: Run a one-line script
        run: echo Hello!

      
      - name: Run a multi-line script
        run: |
          echo hello there,
          echo multiline code in vs code.
